const state={profile:null,resumes:[],vacancies:[]};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const split=v=>v.split(/[,\n]/).map(x=>x.trim()).filter(Boolean);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});if(!response.ok){let detail=`Ошибка ${response.status}`;try{const body=await response.json();detail=Array.isArray(body.detail)?body.detail.map(x=>x.msg).join(', '):body.detail||detail}catch{}throw new Error(detail)}return response.status===204?null:response.json()}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=`toast show${error?' error':''}`;clearTimeout(el.timer);el.timer=setTimeout(()=>el.className='toast',2600)}
function show(view){$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));const titles={overview:'Добрый день',profile:'Профиль кандидата',resumes:'Библиотека резюме',searches:'Стратегия поиска',vacancies:'Вакансии'};$('#page-title').textContent=titles[view];location.hash=view}
$$('.nav-item').forEach(x=>x.onclick=()=>show(x.dataset.view));$$('[data-go]').forEach(x=>x.onclick=()=>show(x.dataset.go));
async function load(){try{const [profile,resumes,vacancies]=await Promise.all([api('/profile'),api('/resumes'),api('/vacancies?limit=100')]);state.profile=profile.profile;state.resumes=resumes;state.vacancies=vacancies;renderAll()}catch(e){toast(e.message,true)}}
function renderAll(){renderMetrics();renderProfile();renderResumes();renderSearches();renderVacancies()}
function renderMetrics(){$('#metric-resumes').textContent=state.resumes.length;$('#metric-searches').textContent=(state.profile.search_profiles||[]).filter(x=>x.enabled).length||state.profile.searches.length;$('#metric-vacancies').textContent=state.vacancies.length}
function renderProfile(){const p=state.profile;$('#profile-name').value=p.name||'';$('#profile-roles').value=(p.target_roles||[]).join(', ');$('#profile-skills').value=(p.skills||[]).join(', ');$('#profile-salary').value=p.minimum_salary||'';$('#profile-remote').checked=p.remote_only;$('#profile-preferences').value=p.preferences||'';$('#profile-facts').value=(p.verified_facts||[]).join('\n')}
$('#profile-form').onsubmit=async e=>{e.preventDefault();try{const data={name:$('#profile-name').value.trim(),target_roles:split($('#profile-roles').value),skills:split($('#profile-skills').value),minimum_salary:Number($('#profile-salary').value)||null,remote_only:$('#profile-remote').checked,preferences:$('#profile-preferences').value.trim(),verified_facts:split($('#profile-facts').value)};const result=await api('/profile',{method:'PATCH',body:JSON.stringify(data)});state.profile=result.profile;renderMetrics();toast('Профиль сохранён')}catch(e){toast(e.message,true)}};
function renderResumes(){const root=$('#resume-list');if(!state.resumes.length){root.innerHTML='<div class="empty">Пока нет резюме. Добавьте первое — текст останется в локальной базе.</div>';return}root.innerHTML=state.resumes.map(r=>`<article class="card"><div class="document-icon">▤</div><h3>${esc(r.name)}</h3><p>${r.target_roles.map(x=>`<span class="tag">${esc(x)}</span>`).join('')||'Роли не указаны'}</p><p>Версия ${r.version}</p><footer><button class="secondary edit-resume" data-id="${r.id}">Изменить</button><button class="secondary archive-resume" data-id="${r.id}">В архив</button></footer></article>`).join('');$$('.edit-resume').forEach(x=>x.onclick=()=>openResume(Number(x.dataset.id)));$$('.archive-resume').forEach(x=>x.onclick=()=>archiveResume(Number(x.dataset.id)))}
async function openResume(id=null){$('#resume-form').reset();$('#resume-id').value=id||'';$('#resume-dialog-title').textContent=id?'Редактировать резюме':'Новое резюме';if(id){try{const r=await api(`/resumes/${id}`);$('#resume-name').value=r.name;$('#resume-roles').value=r.target_roles.join(', ');$('#resume-content').value=r.content}catch(e){return toast(e.message,true)}}$('#resume-dialog').showModal()}
$('#add-resume').onclick=()=>openResume();$('#resume-form').onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return $('#resume-dialog').close();const id=$('#resume-id').value;const data={name:$('#resume-name').value.trim(),target_roles:split($('#resume-roles').value),content:$('#resume-content').value.trim()};try{await api(id?`/resumes/${id}`:'/resumes',{method:id?'PUT':'POST',body:JSON.stringify(data)});state.resumes=await api('/resumes');$('#resume-dialog').close();renderResumes();renderSearches();renderMetrics();toast(id?'Резюме обновлено':'Резюме добавлено')}catch(e){toast(e.message,true)}};
async function archiveResume(id){if(!confirm('Архивировать резюме? История сохранится.'))return;try{await api(`/resumes/${id}`,{method:'PATCH',body:JSON.stringify({archived:true})});state.resumes=await api('/resumes');renderResumes();renderSearches();renderMetrics();toast('Резюме перемещено в архив')}catch(e){toast(e.message,true)}}
function searchTemplate(p={key:'',name:'',enabled:true,resume_id:null,searches:[{text:'',area:null,period:3}]}){return `<article class="search-card"><div class="search-head"><b>${esc(p.name||'Новое направление')}</b><button class="remove-link" type="button">Удалить</button></div><label><span>Ключ</span><input class="sp-key" value="${esc(p.key)}" placeholder="ai-product" /></label><label><span>Название</span><input class="sp-name" value="${esc(p.name)}" placeholder="AI Product" /></label><label><span>Предпочтительное резюме</span><select class="sp-resume"><option value="">Не выбрано</option>${state.resumes.map(r=>`<option value="${r.id}" ${r.id===p.resume_id?'selected':''}>#${r.id} · ${esc(r.name)}</option>`).join('')}</select></label><label class="toggle"><input class="sp-enabled" type="checkbox" ${p.enabled?'checked':''}/><span>Направление включено</span></label><label class="wide"><span>Поисковые запросы — по одному на строку</span><textarea class="sp-queries" rows="4">${esc((p.searches||[]).map(x=>x.text).join('\n'))}</textarea></label></article>`}
function renderSearches(){const root=$('#search-list');const profiles=state.profile.search_profiles||[];root.innerHTML=profiles.length?profiles.map(searchTemplate).join(''):'<div class="empty">Добавьте первое направление поиска.</div>';wireSearchRemove()}
function wireSearchRemove(){$$('.remove-link').forEach(x=>x.onclick=()=>{x.closest('.search-card').remove();if(!$('#search-list').children.length)$('#search-list').innerHTML='<div class="empty">Добавьте первое направление поиска.</div>'})}
$('#add-search').onclick=()=>{if($('#search-list .empty'))$('#search-list').innerHTML='';$('#search-list').insertAdjacentHTML('beforeend',searchTemplate());wireSearchRemove()};$('#save-searches').onclick=async()=>{const profiles=$$('.search-card').map(card=>({key:$('.sp-key',card).value.trim(),name:$('.sp-name',card).value.trim(),enabled:$('.sp-enabled',card).checked,resume_id:Number($('.sp-resume',card).value)||null,searches:split($('.sp-queries',card).value).map(text=>({text,area:null,period:3}))}));try{const result=await api('/profile',{method:'PATCH',body:JSON.stringify({search_profiles:profiles})});state.profile=result.profile;renderSearches();renderMetrics();toast('Направления сохранены')}catch(e){toast(e.message,true)}};
function renderVacancies(){const root=$('#vacancy-list');if(!state.vacancies.length){root.innerHTML='<div class="empty">Вакансий пока нет. Запустите мониторинг — лучшие варианты появятся здесь.</div>';return}root.innerHTML=state.vacancies.map(v=>`<article class="vacancy-card"><div class="score" style="--score:${v.score}"><b>${v.score}%</b></div><div><h3>${esc(v.name)}</h3><p>${esc(v.employer)} · ${(v.search_profiles||[]).map(x=>`${esc(x.name)}${x.resume_id?` · резюме #${x.resume_id}`:''}`).join(' / ')||'Общий поиск'}</p></div><a href="${esc(v.url)}" target="_blank" rel="noopener">Открыть ↗</a></article>`).join('')}
$('#refresh-vacancies').onclick=async()=>{try{state.vacancies=await api('/vacancies?limit=100');renderVacancies();renderMetrics();toast('Список обновлён')}catch(e){toast(e.message,true)}};
show((location.hash||'#overview').slice(1));load();
